version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hawnan_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hawnan
      POSTGRES_PASSWORD: hawnan_password
      POSTGRES_DB: hawnan_db
    ports:
      - "6970:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: hawnan_redis
    restart: unless-stopped
    ports:
      - "6969:6379"

  minio:
    image: minio/minio
    container_name: hawnan_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  pgdata:
  minio-data:
